### ISSUE TITLE
TypeError: Cannot read property 'setNickname' of undefined

### ISSUE THREAD

**Issue by ethamitc** [osu-canada/bot#1]
```
\src\index.js:67
                        usr.setNickname(message.user.ircUsername);
                            ^

TypeError: Cannot read property 'setNickname' of undefined
    at BanchoClient.<anonymous> (A:\source\osu-canada\src\index.js:67:8)
    at BanchoClient.emit (events.js:315:20)
    at MessageCommand.handleCommand (A:\source\osu-canada\node_modules\bancho.js\lib\IrcCommands\MessageCommand.js:24:11)
    at BanchoClient.handleIrcCommand (A:\source\osu-canada\node_modules\bancho.js\lib\BanchoClient.js:245:29)
    at Socket.<anonymous> (A:\source\osu-canada\node_modules\bancho.js\lib\BanchoClient.js:141:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by ethamitc** [comment]
Resolved in 5767910
