### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by ethamitc** [osu-canada/bot#2]
```
TypeError: Cannot read property 'id' of undefined
    at Object.execute (A:\source\osu-canada\src\commands\link.js:15:49)
    at Client.<anonymous> (A:\source\osu-canada\src\index.js:45:11)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (A:\source\osu-canada\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (A:\source\osu-canada\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (A:\source\osu-canada\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (A:\source\osu-canada\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (A:\source\osu-canada\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (A:\source\osu-canada\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (A:\source\osu-canada\node_modules\ws\lib\websocket.js:797:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (A:\source\osu-canada\node_modules\ws\lib\receiver.js:437:14)
    at Receiver.getData (A:\source\osu-canada\node_modules\ws\lib\receiver.js:367:17)
    at Receiver.startLoop (A:\source\osu-canada\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (A:\source\osu-canada\node_modules\ws\lib\receiver.js:78:10)
```

**Comment by ethamitc** [comment]
Resolved in 3b39c15
